# -*- coding: utf-8 -*-
"""_CRAWL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TwdGI8SW1ZgX6XOJoJuMDZ2IGkXdkfhc
"""

!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

import time
import pandas as pd
list_youtube = ['https://www.youtube.com/watch?v=L4MLcHalj1M','https://www.youtube.com/watch?v=5MzfUwXwY2Y','https://www.youtube.com/watch?v=vTJdVE_gjI0']
list_comments = []

driver.get(list_youtube[0])
scrollY = 0

# Thiết lập auto scroll trên website
for i in range(13):
    scrollY += 2000
    driver.execute_script("window.scrollTo(0,{})".format(scrollY))
    time.sleep(1)

# Lệnh gọi tìm kiếm comment thông qua thẻ
a = driver.find_elements_by_xpath("//yt-formatted-string[@id='content-text']")
comments = list(map(lambda x: x.text, a))
comments.pop(0)

# lưu dataframe 
df = pd.DataFrame({'comment': comments})
df.to_csv('GFG_1.csv', encoding="utf-8-sig")
list_comments += comments

driver.get(list_youtube[1])
scrollY = 0

# Thiết lập auto scroll trên website
for i in range(13):
    scrollY += 2000
    driver.execute_script("window.scrollTo(0,{})".format(scrollY))
    time.sleep(1)

# Lệnh gọi tìm kiếm comment thông qua thẻ
a = driver.find_elements_by_xpath("//yt-formatted-string[@id='content-text']")
comments = list(map(lambda x: x.text, a))
comments.pop(0)

# lưu dataframe 
df = pd.DataFrame({'comment': comments})
df.to_csv('GFG_2.csv', encoding="utf-8-sig")
list_comments += comments

driver.get(list_youtube[2])
scrollY = 0

# Thiết lập auto scroll trên website
for i in range(13):
    scrollY += 2000
    driver.execute_script("window.scrollTo(0,{})".format(scrollY))
    time.sleep(1)

# Lệnh gọi tìm kiếm comment thông qua thẻ
a = driver.find_elements_by_xpath("//yt-formatted-string[@id='content-text']")
comments = list(map(lambda x: x.text, a))
comments.pop(0)

# lưu dataframe 
df = pd.DataFrame({'comment': comments})
df.to_csv('GFG_3.csv', encoding="utf-8-sig")
list_comments += comments

for i in list_comments:
  print(i)

len(list_comments)